### ISSUE TITLE
[Refactor] SwiftLint에서 발생하는 Warning 수정

### ISSUE THREAD

**Issue by ChoiysApple** [YAPP-Github/20th-ALL-Rounder-Team-1-iOS#195]
## 현재 동작
SwiftLint를 사용하였지만 코딩 컨벤션에 따르지 않은 부분을 컨벤션에 맞게 수정

## 기대 동작

- [x] `API.swift` 파일을 검수 파일에서 제외
- [ ] `Pod` 폴더를 검수 파일에서 제외
- [ ] 편의를 위해 `exclude`한 `rule`이 있는지 확인
- [ ] 해결되거나 폐기된 `// TODO` 삭제
- [ ] `SwiftLint`에서 발생하는 컨벤션 `warning` 해결

**Comment by ChoiysApple** [comment]
### 1. Redundant String Enum Value Violation: (redundant_string_enum_value)
> String 타입의 Enum에서 동일한 값이라면 중복으로 쓰지 않아도 사용할 수 있어 삭제하였다.
```swift
// 수정 전
enum CategoryOpenType: String {
    case allOpen = "allOpen"
    case followerOpen = "followerOpen"
    case closed = "closed"

// 수정 후
enum CategoryOpenType: String {
    case allOpen
    case followerOpen
    case closed

```

### 2. Redundant Optional Initialization Violation: (redundant_optional_initialization)
> Optional 타입의 프로퍼티는 기본적으로 nil로 초기화되기 때문에 중복이 일어나기 때문에 수정해 준다
```swift
// 수정 전
struct SignUpModel {
    var email: String? = nil
    var password: String? = nil
    var nickname: String? = nil
    var jobs: [String]? = nil
    var interests: [String]? = nil
    var signUpAgreed: Bool? = nil
}

// 수정 후
struct SignUpModel {
    var email: String?
    var password: String?
    var nickname: String?
    var jobs: [String]?
    var interests: [String]?
    var signUpAgreed: Bool?
}
```

**_`ScheduleEditViewModel.swift` `ScheduleModifyViewModel.swift`_**
```swift
// 수정 전
var previousTag: DateTime? = nil

// 수정 후
var previousTag: DateTime?
```

### 3. Redundant Discardable Let Violation: (redundant_discardable_let)
> 이미 `@discardableResult` 처리가 되어있기 때문에 `let _ ` 처리가 필요없다

**_`CategoryEditViewController.swift` `CategoryListViewController.swift` `ScheduleDetailViewController.swift` `DayRepeatViewController.swift` `CategoryListSheetViewController.swift` `WeekRepeatViewController.swift` `AddInformationViewController.swift` `SignUpTermsViewController.swift` `PasswordFindViewController.swift` `AlertPopupViewController.swift` `AuthPopupViewController.swift` `WarningPopupViewController.swift`_**

```swift
// 수정 전
let _ = viewModel?.transform(input: input)

// 수정 후
viewModel?.transform(input: input)
```

### 4. Closure Parameter Position Violation: (closure_parameter_position)
> 클로저 파라미터는 opening brace와 같은 Line에 있어야 한다

**_`OpenTypeStackView.swift` `ScheduleCompleteToolBar.swift` `WeekRepeatViewController.swift`_**

```swift
// 수정 전
        let layout = UICollectionViewCompositionalLayout { (_: Int,
            _ : NSCollectionLayoutEnvironment) -> NSCollectionLayoutSection in

// 수정 후
    let layout = UICollectionViewCompositionalLayout { (_: Int, _ : NSCollectionLayoutEnvironment) -> NSCollectionLayoutSection in
```

**_`ScheduleEditViewModel.swift`_**

```swift
// 수정 전
input.confirmButtonDidTapEvent.withLatestFrom(combinedInputs)
            .subscribe(onNext: { [weak self] dates, nameText, category,
                                             repeatType, repeatSelectValue, repeatEnd, memo in

// 수정 후
input.confirmButtonDidTapEvent.withLatestFrom(combinedInputs)
            .subscribe(onNext: { [weak self] dates, nameText, category, repeatType, repeatSelectValue, repeatEnd, memo in
```


### 5. Implicit Getter Violation: (implicit_getter)
> 읽기 전용 Computed Property는 get 키워드 사용을 자제해야 한다

```swift
override var bottomSheetHeight: CGFloat {
        get {
            return 350
        }
    }
```
현재 모든 bottomSheet가 getter를 이용해 구현되어 있어 수정 보류

### 6. No Space in Method Call Violation: (no_space_in_method_call)
> 메호드 호출시 메소드이름과 소괄호 사이에 개행이 없어야 한다

**_`MonthlyCalendarSheetViewModel.swift`_**
```swift
// 수정 전
input.didTapConfirmButton.subscribe (onNext: { _ in

// 수정 후
input.didTapConfirmButton.subscribe(onNext: { _ in
```

### 7. Todo Violation: (todo)
> 모든 TODO가 해결되어야 함

**_`StickerAddSheet.swift`_**
```swift
// TODO: 작동 안함 -> 수정 필요
extension StickerAddSheetViewController: UICollectionViewDelegate {
```
작동하는 것으로 확인해서 삭제 

### 8. Vertical Parameter Alignment Violation: (vertical_parameter_alignment)
> 파라미터를 세로로 나열할 때는 정렬이 되어 있어야 한다

**_`ProfileCoordinator.swift`_**
```swift
// 수정 전
    func presentAlertPopupViewController(titleText: String,
                                               informText: String,
                                               confirmButtonText: String,
                                               cancelButtonText: String,
                                               completionHandler: @escaping () -> Void) {

// 수정 후
    func presentAlertPopupViewController(titleText: String,
                                         informText: String,
                                         confirmButtonText: String,
                                         cancelButtonText: String,
                                         completionHandler: @escaping () -> Void) {
```

### 9. Opening Brace Spacing Violation: (opening_brace)
> 같은 라인에서 개행은 한번만 가능하다

_**`PasswordChangeViewController.swift`**_

```swift
// 수정 전
if ($0.textField.text ?? "").isEmpty  { isFieldsFilled = false }

// 수정 후
if ($0.textField.text ?? "").isEmpty { isFieldsFilled = false }
```

### 10. Colon Spacing Violation: (colon)
> identifier 뒤의 콜론을 쓸 때는 개행이 없이 사용한다

**_`ProfileEditViewController.swift`_**

```swift
// 수정 전
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey : Any])

// 수정 후
func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [UIImagePickerController.InfoKey: Any])
```

### 11. Result of call to <...> is unused

이 경고를 발생시키는 함수들에 `@discardableResult` 처리

**Comment by ChoiysApple** [comment]
<img width="268" alt="image" src="https://user-images.githubusercontent.com/43776784/183830776-b6061cf4-dbdc-45c2-81c3-922ba666d740.png">

> Warning 363개 -> 33개

**Comment by ChoiysApple** [comment]
### **_`.swiftlint.yml`_** 수정

```swift
// disabled_rules 에서 삭제
- force_cast

// disabled_rules에 추가
- unused_closure_parameter
- implicit_getter
```
수정 후 발생하는 error에도 대응 완료

### 수정 후 
<img width="268" alt="image" src="https://user-images.githubusercontent.com/43776784/183833418-45573b2e-7391-41fb-8630-3059d1f2ddfb.png">
> Warning 33개 -> 18개
